name-template: $NEXT_PATCH_VERSION
tag-template: $NEXT_PATCH_VERSION
categories:
  - title: 🚀 Features
    labels:
      - enhancement
      - feature
  - title: 🐛 Bug Fixes
    labels:
      - bugfix
      - fix
      - bug
version-resolver:
    major:
      labels:
        - 'ver-major'
    minor:
      labels:
        - 'ver-minor'
    patch:
      labels:
        - 'ver-patch'
    default: minor
template: |
  ## Changes

  $CHANGES
