name-template: $NEXT_PATCH_VERSION
tag-template: $NEXT_PATCH_VERSION
categories:
  - title: 🚀 Features
    labels:
      - enhancement
      - feature
  - title: 🐛 Bug Fixes
    labels:
      - bugfix
      - fix
      - bug
version-resolver:
    major:
      labels:
        - 'major'
    minor:
      labels:
        - 'minor'
    default: patch
template: |
  ## Changes

  $CHANGES
