name: organic-wp-plugin

x-vars:
  db-password: &db-password organicwpplugin
  db-user: &db-user root

x-templates:
  base-wordpress: &base-wordpress
    depends_on:
      db:
          condition: service_healthy
    volumes:
      - ./:/var/www/html/wp-content/plugins/wordpress-plugin:ro
      - ./dev/fixtures.yml:/tmp/dev/fixtures.yml:ro
  base-environment: &base-environment
    WORDPRESS_DB_HOST: db
    WORDPRESS_DB_USER: *db-user
    WORDPRESS_DB_PASSWORD: *db-password
    ORGANIC_ENVIRONMENT: ${ORGANIC_ENVIRONMENT}
    ORGANIC_API_URL: ${ORGANIC_API_URL}
    ORGANIC_CDN_URL: ${ORGANIC_CDN_URL}

services:
  wp49-php72:
    build:
      context: ./dev
      target: wp49-php72
    <<: *base-wordpress
    ports:
      - 8031:80
    environment:
      <<: *base-environment
      WORDPRESS_DB_NAME: wp49_php72

  wp59-php74:
    build:
      context: ./dev
      target: wp59-php74
    <<: *base-wordpress
    ports:
      - 8032:80
    environment:
      <<: *base-environment
      WORDPRESS_DB_NAME: wp59_php74

  wp61-php74:
    build:
      context: ./dev
      target: wp61-php74
    <<: *base-wordpress
    ports:
      - 8033:80
    environment:
      <<: *base-environment
      WORDPRESS_DB_NAME: wp61_php74

  wp61-php82:
    build:
      context: ./dev
      target: wp61-php82
    <<: *base-wordpress
    ports:
      - 8034:80
    environment:
      <<: *base-environment
      WORDPRESS_DB_NAME: wp61_php82

  db:
    image: mysql:8.0.32-oracle
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3330:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 5s
      timeout: 3s
      retries: 2
    environment:
      MYSQL_ROOT_PASSWORD: *db-password
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: {}
