name: Code Quality Checks
on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize
jobs:
  build:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
        with:
          working_dir: src
          php_version: "7.4"
          php_extensions: zip

      - name: Run PHPCS
        run: cd src && composer run lint

      - name: Run PHPUnit
        run: cd src && composer run phpunit -- --exclude-group selenium_test

      - name: Run ESLint
        run: cd src && composer run eslint

  selenium-tests:
    name: Selenium Tests
    runs-on: ubuntu-latest
    env:
      # ECR_BACKEND_REPOSITORY: organic-platform-backend
      PROJECT: wordpress-plugin
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build the stack
        id: build-stack
        run: |
          ORGANIC_DEMO_SITE_API_KEY="${{ secrets.ORGANIC_DEMO_SITE_API_KEY }}" \
          COMPOSER_AUTH="${{ secrets.GITHUB_TOKEN }}" \
          docker compose -p ${{ env.PROJECT }} \
          --env-file .env.ci \
          -f docker-compose.yml up -d

      - name: Run selenium tests
        run: |
          docker compose -p ${{ env.PROJECT }} exec \
          bash -c "cd src && ./vendor/bin/phpunit --group selenium_test"

      # Stop running containers and clean-up
      - name: Clean up
        if: always()
        run: |
          docker compose -p ${{ env.PROJECT }} -f docker-compose.yml down --remove-orphans --volumes