name: Code Quality Checks
on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize
jobs:
  build:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP with composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: zip
          tools: composer

      - name: Install dependencies
        run: cd src && composer install

      - name: Run PHPCS
        run: cd src && composer run lint

      - name: Run PHPUnit
        run: cd src && composer run phpunit -- --exclude-group selenium_test

      - name: Run ESLint
        run: cd src && composer run eslint
