name: Code Quality Checks
on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize
jobs:
  build:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
        with:
          working_dir: src
          php_version: "7.4"

      - name: Run PHPCS
        run: cd src && composer run lint

      - name: Run PHPUnit
        run: cd src && composer run phpunit

      - name: Run ESLint
        run: cd src && composer run eslint
