name: Build Plugin Dev Zip and Push to S3

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize

permissions:
   checks: write
   contents: write
   id-token: write
   packages: write
   statuses: write

jobs:
  deploy:
    name: 'Organic Ad Wordpress: Build Dev Release'
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-west-2
      AWS_BUCKET: empire-wordpress-plugin
      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
      BUILD_NUMBER: dev-${{ github.event.pull_request.number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP with composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: zip
          tools: composer:2.5.5

      # Create a packaged up zip file
      - name: Set Version Number & Build Zip
        id: build-zip
        run: ./build-zip.sh ${{ env.BUILD_NUMBER }}

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/GitHubActionIAMRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload Dev Build
        uses: actions/upload-artifact@v3
        with:
          name: organic-${{ env.BUILD_NUMBER }}.zip
          path: build/organic-${{ env.BUILD_NUMBER }}.zip

      # Push zip to S3 for easy integration with Organic Platform
      - name: Deploy
        run: |
          aws s3 cp build/organic-${{ env.BUILD_NUMBER }}.zip s3://${{ env.AWS_BUCKET }}/organic-${{ env.BUILD_NUMBER }}.zip
          aws s3api put-object-acl --bucket ${{ env.AWS_BUCKET }} --key organic-${{ env.BUILD_NUMBER }}.zip --acl public-read
