name: Integration Tests
on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize

jobs:
  selenium-tests:
    name: Build the project
    strategy:
      fail-fast: false
      matrix:
        wp_service: [ 'wp59-php74', 'wp61-php74', 'wp61-php82' ]
    runs-on: ubuntu-latest
    env:
      PROJECT: wordpress-plugin
      ORGANIC_DEMO_SITE_APIKEY: ${{ secrets.ORGANIC_DEMO_SITE_API_KEY }}
      COMPOSER_AUTH: '{"github-oauth":{"github.com":"${{ secrets.GITHUB_TOKEN }}"}}'
    steps:
      - uses: actions/checkout@v3
      - name: Configure poetry
        run: curl -sSL https://install.python-poetry.org | python3 -
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      - run: poetry self add poetry-dotenv-plugin
      - run: poetry install

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: src/vendor
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Build the stack
        run: |
          mv .env.ci .env
          composer config --global github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}
          poetry run ./dev.py up ${{ matrix.wp_service }}

      - name: Run selenium tests (${{ matrix.wp_service }})
        run: |
          poetry run ./dev.py run-tests ${{ matrix.wp_service }} --limit_to selenium_test
