name: Integration Tests
on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest
    env:
      PROJECT: wordpress-plugin
      ORGANIC_DEMO_SITE_APIKEY: ${{ secrets.ORGANIC_DEMO_SITE_API_KEY }}
      COMPOSER_AUTH: '{"github-oauth":{"github.com":"${{ secrets.GITHUB_TOKEN }}"}}'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up python
        id: python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Configure poetry
        run: |
          poetry self add poetry-dotenv-plugin
          poetry install

      - name: Build the stack
        run: |
          mv .env.ci .env
          composer config --global github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}
          poetry run ./dev.py up wp49-php72 wp59-php74 wp61-php74 wp61-php82


  selenium-tests-wp59-php74:
    name: Selenium Tests WP59-PHP74
    runs-on: ubuntu-latest
    needs: build
    env:
      PROJECT: wordpress-plugin
      ORGANIC_DEMO_SITE_APIKEY: ${{ secrets.ORGANIC_DEMO_SITE_API_KEY }}
      COMPOSER_AUTH: '{"github-oauth":{"github.com":"${{ secrets.GITHUB_TOKEN }}"}}'
    steps:
      - name: Run selenium tests (WP59-PHP74)
        run: |
          poetry run ./dev.py run-tests wp59-php74 --limit_to selenium_test


  selenium-tests-wp61-php74:
    name: Selenium Tests WP61-PHP74
    runs-on: ubuntu-latest
    needs: build
    env:
      PROJECT: wordpress-plugin
      ORGANIC_DEMO_SITE_APIKEY: ${{ secrets.ORGANIC_DEMO_SITE_API_KEY }}
      COMPOSER_AUTH: '{"github-oauth":{"github.com":"${{ secrets.GITHUB_TOKEN }}"}}'
    steps:

      - name: Run selenium tests (WP61-PHP74)
        run: |
          poetry run ./dev.py run-tests wp61-php74 --limit_to selenium_test
