name: PHPUnit
on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize
jobs:
  build:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - name: Run PHPUnit
        run: composer run phpunit
