name: Publish plugin to Wordpress.org

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish plugin to Wordpress.org
    runs-on: ubuntu-latest

    steps:
      - uses: voxmedia/github-action-slack-notify-build@v1
        id: slack
        with:
          channel: dev-notifications
          status: STARTED
          color: warning
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - uses: cardinalby/git-get-release-action@v1
        id: latest_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          latest: true

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.latest_release.outputs.tag_name }}

      - name: Setup PHP with composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: zip
          tools: composer:2.5.5

      - name: Build plugin
        run: ./build-zip.sh ${{ steps.latest_release.outputs.tag_name }}

      - name: Upload plugin to Wordpress.org
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.WORDPRESS_ORG_SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.WORDPRESS_ORG_SVN_USERNAME }}
          BUILD_DIR: build/organic
          VERSION: ${{ steps.latest_release.outputs.tag_name }}
          SLUG: organic

      # Pre-configured step to send notification on build success
      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: dev-notifications
          status: SUCCESS
          color: good

      # Pre-configured step to send notification on build failure
      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: dev-notifications
          status: FAILED
          color: danger